### ISSUE TITLE
It doesn't work at all

### ISSUE THREAD

**Issue by rgreco87** [mccoy88f/JDownloader-Launcher-M1-ARM64#2]
I followed *all* your instruction but the launcher simply doesn't work. Whenever I try to open it it closes itself in less than a while and nothing happens. Can you please give detailed instructions about how to get it to work?

**Comment by rgreco87** [comment]
Are you @mccoy88f going to take this issue seriously?

**Comment by mccoy88f** [comment]
Please tell me where your jdownloader folder is.

**Comment by rgreco87** [comment]
> Please tell me where your jdownloader folder is.

I fixed it by myself, thank you. Anyway, the launcher doesn’t ask for external hard drive permission so JDownloader can’t extract files to external disks. I can’t find a solution for that. @mccoy88f

**Comment by raziel2001au** [comment]
I haven't personally run into this issue with JDownloader, but I have run into something similar with another Java-based application. As I mentioned before, the app just runs whatever the shell script tells it to, it's ultimately the Java binary that runs JDownloader, so you probably need to give Java itself full disk access on your Mac:
1) Open the Terminal
2) Execute the following command to find the path to your java executable: which java
3) For me this was '/usr/bin/java', so in finder I selected Go->Go to Folder and had it open a folder to '/usr/bin'
4) Open System Preferences->Security & Privacy->Privacy
5) Click the lock to allow you to make changes
6) Open 'Full Disk Access' from the left hand side
7) Drag and drop the Java binary to the box on the right and ensure it is ticked to allow full disk access.

For good measure I'd also do the same to JDownloader.app, though I don't think it's necessary since it's Java that's running JDownloader, not the app itself which is just a simple shell script. Try that and see if it fixes your problem. Also, give @mccoy88f a break, people working on open source projects aren't exactly paid for support. When you download something from GitHub, the assumption is that you'll be technical enough to use what you've downloaded.

**Comment by PivotMasterNM** [comment]
having the same issue - your fix sounds plausible, but given java's mixed track record in regards to security, I would rather not give it full disk access.

**Comment by raziel2001au** [comment]
I wouldn't call it a fix, more a theory. OSX unfortunately has many layers of security which is meant to protect the average user, but often ends up making things more complicated. If you do come up with a fix, please post the solution for other users as well.

**Comment by PivotMasterNM** [comment]
I just came across an alpha official build, seems like native support via an installer is coming very soon. The alpha works great for me and behaves identical to the rosetta official stable application.

Appreciate you guy's workaround though.

https://board.jdownloader.org/showthread.php?t=86029&page=2

**Comment by raziel2001au** [comment]
Nice, I'm going to give this a spin, I'm quite keen for a fully supported M1 build so we don't need to use workarounds to get there.

**Comment by raziel2001au** [comment]
Okay, the official Apple M1 build of JDownloader has now been released and can be downloaded from:
https://jdownloader.org/download/index

I've been testing this release and it seems to work well, so I think we no longer need to use a wrapper script to run the software on the M1 version of Java. I'd suggest switching to the official release of JDownloader and seeing if that solves your issue @xazac. If so, you can close the issue.

**Comment by mccoy88f** [comment]
Yes, is no longer needed to use this app. Thanks to all.
Have a nice 2022

**Comment by rgreco87** [comment]
> Okay, the official Apple M1 build of JDownloader has now been released and can be downloaded from: https://jdownloader.org/download/index
> 
> I've been testing this release and it seems to work well, so I think we no longer need to use a wrapper script to run the software on the M1 version of Java. I'd suggest switching to the official release of JDownloader and seeing if that solves your issue @xazac. If so, you can close the issue.

Really thanks! @mccoy88f
